Repository Team-TMB/client, pull requests merged in 2024-02, with the labels that each got.

#41 [Feature] 토큰 사용을 위한 개발용 api 연결
  src/components/login/LoginButton.scss
  src/components/login/LoginButton.tsx
  src/components/login/LoginSection.scss
  src/components/login/LoginSection.tsx
  src/lib/api/authAPI.ts
  src/lib/api/commonAPI.ts
Labels: Feature, Html&Css

#45 [Feature] modal 커스텀 훅 생성
  public/images/modalcloseicon.svg
  src/app/layout.tsx
  src/components/common/Modal.scss
  src/components/common/Modal.tsx
  src/lib/hooks/useModal.ts
  src/lib/store/modalState.ts
Labels: Feature

#47 [!HOTFIX] localStorage에 토큰값이 undefined로 저장되는 버그 긴급 수정
  src/components/login/LoginButton.tsx
  src/lib/api/authAPI.ts
  src/lib/api/commonAPI.ts
  src/lib/api/instance.ts
  src/lib/api/signupAPI.ts
  src/lib/api/todayAPI.ts
Labels: bug

#52 [Chore] husky 도입
  .eslintrc.json
  .pnp.cjs
  package.json
  src/lib/api/authAPI.ts
  src/lib/api/commonAPI.ts
  src/lib/api/instance.ts
  src/lib/api/signupAPI.ts
  src/lib/api/todayAPI.ts
  yarn.lock
Labels: Feature

#54 [Refactor] 중간 배포 설정
  src/components/comment/Comment.tsx
  src/components/comment/CommentListItem.tsx
  src/components/common/Modal.tsx
  src/components/signup/Buttons/SignupButtons.tsx
  src/components/signup/SignupStepTwo.tsx
  src/components/today/Today.tsx
  src/lib/api/commonAPI.ts
  src/lib/api/instance.ts
  src/lib/api/todayAPI.ts
  src/stories/Page.tsx
Labels: Refactor

#55 [Refactor] Layout 컴포넌트 리팩토링
  src/app/layout.tsx
  src/components/comment/Comment.scss
  src/components/comment/Comment.tsx
  src/components/comment/CommentList.tsx
  src/components/comment/CommentListItem.tsx
  src/components/common/Layout.tsx
  src/lib/util/getGameTime.ts
Labels: Refactor

#56 [Refactor] 회원가입 페이지 리팩토링
  src/components/common/TeamCards.scss
  src/components/common/TeamCards.tsx
  src/components/signup/SignupStepOne.tsx
  src/components/signup/SignupStepTwo.tsx
  src/components/signup/TeamsInfo.ts
  src/lib/api/commonAPI.ts
  src/lib/api/signupAPI.ts
  src/lib/store/signup/teamsStore.ts
Labels: Refactor
